### ISSUE TITLE
EventEmitter memory leak warning

### ISSUE THREAD

**Issue by lionep** [rodrigopolo/mimovie#1]
After several use of the lib, it seems that a memory leak exists : 

```
(node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at module.exports (/Users/lionel/demo/node_modules/mimovie/lib/mimovie.js:57:10)
```

**Comment by rodrigopolo** [comment]
Thanks you, I have modified the code in order to remove each listener when mediainfo exits. I did some tests running more than 20 sync calls to the lib and the warning apear again, but it is only a warning, there is no more memory leak. NOTICE: calling more than 2 or 3 mediainfo instances at the same time could be a bad idea, mediainfo is hardrive intensive, I recommend using a queued/async approach. I did the very same test using an async approach and I got no memory leak warnings and the script executed faster.
